### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by NIFTY-SKIDDIE** [malockey/bot-report-tiktok#1]
Any instructions on how to run this on a Windows machine by any chance?

**Comment by malockey** [comment]
Configuring libcurl on a Windows machine is quite difficult and, in my opinion, somewhat unnecessary. What I advise is to install WSL, install libcurl and mingw on the WSL machine, then connect to WSL (bottom left, green button in VSCode), and finally execute the command to compile and run the application: g++ mass_report_bot.cpp -o mass_report_bot -lcurl && ./mass_report_bot.
